name: xstore
description: A new Flutter project.


publish_to: 'none' 



version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'



dependencies:
  flutter:
    sdk: flutter

  # Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.2
  
  # State Mangament
  get: ^4.6.5
  get_storage: ^2.1.1

  # Product Specific
  readmore: ^2.2.0
  carousel_slider: ^4.2.1

  # Fonts
  google_fonts: ^6.1.0

  # Utility Packages
  http: ^1.1.0
  intl: ^0.18.1
  logger: ^2.0.2+1
  lottie: ^2.6.0
  connectivity_plus: ^5.0.2
  image_picker: ^1.0.7
  shimmer: ^3.0.0
  url_launcher: ^6.1.14
  flutter_native_splash: ^2.3.5
  smooth_page_indicator: ^1.1.0


  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  google_sign_in: ^6.1.6
  firebase_storage: ^11.6.0
  cached_network_image: ^3.3.1
  
  
 
  

  

dev_dependencies:
  flutter_test:
    sdk: flutter

  

  
  flutter_lints: ^2.0.0
  



flutter:

  
  uses-material-design: true

  
  assets:
    - assets/icons/brands/
    - assets/icons/categories/
    - assets/icons/social/
    - assets/logos/
    - assets/promos/
    - assets/images/onboarding/
    - assets/images/animations/
    - assets/images/banners/
    - assets/images/products/
  fonts:
    - family: Schyler
  
  
  
  
  
  
  
  
  
  
  
  
