// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDW3Izk9rnYSEp4X2k3J70Hz2rs5xcURGs',
    appId: '1:309897946718:web:912d2ed5405e42e0d676cf',
    messagingSenderId: '309897946718',
    projectId: 'xstore-a8fbc',
    authDomain: 'xstore-a8fbc.firebaseapp.com',
    storageBucket: 'xstore-a8fbc.appspot.com',
    measurementId: 'G-Z3179E30RZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRV4wrVc_ENakD1p3-fm9IBB1Qa64Pvgs',
    appId: '1:309897946718:android:303489d622630e42d676cf',
    messagingSenderId: '309897946718',
    projectId: 'xstore-a8fbc',
    storageBucket: 'xstore-a8fbc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCc4an0lY2SBBkVytWYlbHVDSw2NKnjCFg',
    appId: '1:309897946718:ios:49cf0cedf4da5611d676cf',
    messagingSenderId: '309897946718',
    projectId: 'xstore-a8fbc',
    storageBucket: 'xstore-a8fbc.appspot.com',
    androidClientId: '309897946718-er120cjun9gg4ugg42fjfilp6ch1a71l.apps.googleusercontent.com',
    iosClientId: '309897946718-s2qcg6um6da29mosl3mat0mstb6mh2t8.apps.googleusercontent.com',
    iosBundleId: 'com.example.xstore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCc4an0lY2SBBkVytWYlbHVDSw2NKnjCFg',
    appId: '1:309897946718:ios:ab4017eb803f7141d676cf',
    messagingSenderId: '309897946718',
    projectId: 'xstore-a8fbc',
    storageBucket: 'xstore-a8fbc.appspot.com',
    androidClientId: '309897946718-er120cjun9gg4ugg42fjfilp6ch1a71l.apps.googleusercontent.com',
    iosClientId: '309897946718-81p7vdhe152gmdr3818j6upm3ua7m4ub.apps.googleusercontent.com',
    iosBundleId: 'com.example.xstore.RunnerTests',
  );
}
